config/routes.rb
Rails.application.routes.draw do

  root              'static_pages#home'

  get 'help'     => 'static_pages#help'

  get  'contact' => 'static_pages#contact'

  get  'about'   => 'static_pages#about'

  get 'signup' => 'users#new'

  get 'login' => 'sessions#new'

  post 'login' => 'sessions#create'

  delete 'logout' => 'sessions#destroy'

  resources :users do

    resources :courses do

      resources :subjects 

    end

  end

  resources :user_tasks

  namespace :supervisors  do
    match '/login', to: 'sessions#new', via: 'get'
    match '/logout', to: 'sessions#destroy', via: 'delete'
    resources :sessions, only: [:new, :create, :destroy]
    resources :users
    resources :subjects
    resources :courses do
      resources :users
    end
    resources :users_courses, only: [:index, :create]
  end
  

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
	before_action :logged_in_user, only: [:index, :show]

	def index
		# @user = User.find_by(id: session[:user_id])
		@user = User.find_by(id: params[:user_id])
		@courses = @user.courses.all
	end

	def show
		@course = Course.find_by(id: params[:id])
		
	end

	def new
		
	end

	def create
		
	end

	def edit
		
	end

	def update
		
	end

	def destroy
		
	end

private


end

app/controllers/supervisors/courses_controller.rb
class Supervisors::CoursesController < ApplicationController
	before_action :logged_in_user, only: [:show]
	before_action :logged_in_supervisor, only: [:index, :new, :create, :edit, :update, :delete]
	def index
		@courses = Course.all
		@users = User.where(supervisor: false).all
	end

	def show
		@course = Course.find_by(id: params[:id])
		session[:course_id] = @course.id
	end

	def new
		@course = Course.new
	end

	def create
		@course = Course.new(course_params)
		if @course.save
			flash[:success] = "New course created"
			redirect_to supervisors_courses_url
		else
			render 'new'
		end
	end

	def edit
		@course = Course.find_by(id: params[:id])
	end

	def update
		@course = Course.find_by(id: params[:id])
		if @course.update_attributes(course_params)
			flash[:success] = "Course information updated"
			redirect_to supervisors_course_url(@course)
		else
			render 'edit'
		end
	end

	def destroy
		Course.find_by(id: params[:id]).destroy
		redirect_to supervisors_courses_url
	end

	

private

	# strong paramaters
	def course_params
		params.require(:course).permit(:name, :description)
	end

end

app/controllers/supervisors/sessions_controller.rb
class Supervisors::SessionsController < ApplicationController
  def new

  end

  def create
  	supervisor = User.find_by(email: params[:session][:email].downcase)
  	if( supervisor && supervisor.authenticate(params[:session][:password]) && supervisor.supervisor?)
  		log_in supervisor
  		redirect_to supervisors_user_url(supervisor)
  	else
      if ( supervisor && !supervisor.supervisor?)
        flash.now[:danger] = 'Not supervisor'
  		else
        flash.now[:danger] = 'Invalid email/password combination'
      end
  		render 'new'
  	end
  end

  def destroy
  	log_out
  	redirect_to root_url
  end

end

app/controllers/supervisors/subjects_controller.rb
class Supervisors::SubjectsController < ApplicationController
	def index
		@subjects = Subject.all.paginate(page: params[:page])
	end

	def show
		@subject = Subject.find_by(id: params[:id])
	end

	def new
		@subject = Subject.new
	end

	def create
		
	end

	def edit
		@subject = Subject.find_by(:id => params[:id])
	end

	def update
		@subject = Subject.find_by(id: params[:id])

    	@subject.update_attributes(name: params[:subject][:name], description: params[:subject][:description], instruction: params[:subject][:instruction])
    	if params[:task][:name] != ""
    		@task = Task.new(name: params[:task][:name], subject_id: params[:id])
    		@task.save
    	end
      flash[:success] = "Subject information updated"
      redirect_to supervisors_subject_url(@subject)
    
	end

	def destroy
		
	end

	# test
	def course
		
	end

end

app/controllers/supervisors/users_controller.rb
class Supervisors::UsersController < ApplicationController
  before_action :logged_in_supervisor, only: [:update, :edit]
  before_action :correct_user, only: [:edit, :update]

	def index
		@supervisors = User.where(supervisor: true).all 
    @course = Course.find_by(id: params[:course_id])
    @users = @course.users
	end

  def show
  	@supervisor = User.find(params[:id])
   
  end

 # GET /users/
  def new
  	
  	@supervisor = User.new
  end

  def create
  	@supervisor = User.new(user_params)

  	if @supervisor.save
  		log_in @supervisor
  		# add to flash variable (need to render in views)
  		flash[:success] = "Welcome to ruby on rails"
  		redirect_to superviosrs_user_url(@supervisor)
  	else
  		render 'new'
  	end
  end

  def edit
    @supervisor = User.find_by(id: params[:id])
  end

  def update
    @supervisor = User.find_by(id: params[:id])

    if @supervisor.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to supervisors_user_url(@supervisor)
    else
      render 'edit'
    end
  end

  def destroy
    User.find_by(id: params[:id]).destroy
    redirect_to supervisors_users_url
  end

private
	def user_params
		params.require(:supervisor).permit(:name, :email, :password, :password_confirmation)
	end

  
end

app/controllers/supervisors/users_courses_controller.rb
class Supervisors::UsersCoursesController < ApplicationController
	before_action :logged_in_user, only: [:index]
	def index
		@course = Course.find_by(id: session[:course_id])
		@users_courses = @course.users.paginate(page: params[:page])
	end

	def create
		@users_id = params[:users]
		@course_id = params[:course]

		@users_id.each do |u|
			@uc = UserCourse.find_by(user_id: u.to_i, course_id: @course_id.to_i)
			if @uc.nil?
				@uc = UserCourse.new(user_id: u.to_i, course_id: @course_id.to_i)
				@uc.save
			end
		end

		@courses = Course.all
		redirect_to supervisors_courses_path

	end

end

app/helpers/supervisors/sessions_helper.rb
module Supervisors::SessionsHelper
	def log_in(user)
		session[:user_id] = user.id
		
	end

	def current_user
		@current_user ||= User.find_by(id: session[:user_id])
		
	end

	def logged_in?
		!current_user.nil?
	end

	def log_out
		session.delete(:user_id)
		@current_user = nil
	end

	def logged_in_supervisor
	    unless logged_in? && current_user.supervisor?
	    	log_out
	      	flash[:danger] = "Please log in (as a supervisor)."
	      	redirect_to supervisors_login_url
	    end
  	end


end

app/helpers/supervisors/users_controller_helper.rb
module Supervisors::UsersControllerHelper
end

app/views/supervisors/courses/_course.html.erb
<li>
  	<!-- co anh o day -->
  	<%= course.name %> | 
  	<%= link_to "Details", supervisors_course_path(course) %> | 
  	<%= link_to "Delete", supervisors_course_path(course), method: :delete, data: {confirm: "Are you sure? "} %>
</li>

app/views/supervisors/courses/edit.html.erb
<% provide(:title, "Edit course") %>
<h1>Edit course information</h1>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= render 'shared/error_messages_course'  %>

		<%= form_for(:course, url: supervisors_course_path(@course), html:{method:'patch'}) do |f|  %>

			<%= f.label "Course name"  %>
			<%= f.text_field :name, class: "form-control" %>

			<%= f.label "Description" %>
			<%= f.text_field :description, class: "form-control" %>

			<%= f.submit("Save changes", class: "btn btn-primary") %>
		<% end  %>
	</div>
</div>

app/views/supervisors/courses/index.html.erb
<h1> All courses </h1>


<ul class="courses">
	
  <%= render @courses %>
</ul>





<p class="btn btn-primary">
 <%= link_to "Create a new course", new_supervisors_course_path %>
</p>

<p><b>Assign trainees to a course</b></p>
<p>
	<%= form_tag(supervisors_users_courses_path) do %>
	<%= select_tag("course", options_from_collection_for_select(@courses, "id", "name")) %>
	<%= select_tag("users[]", options_from_collection_for_select(@users, "id", "name"), multiple: true  ) %>
	<%= submit_tag "Assign" %>

	<% end %>
</p>

app/views/supervisors/courses/new.html.erb
<% provide(:title, "Create new course") %>
<h1>Create new course</h1>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= render 'shared/error_messages_course'  %>

		<%= form_for(:course, url: supervisors_courses_path) do |f|  %>

			<%= f.label "Course name"  %>
			<%= f.text_field :name, class: "form-control" %>

			<%= f.label "Description" %>
			<%= f.text_field :description, class: "form-control" %>

			<%= f.submit("Create new course", class: "btn btn-primary") %>
		<% end  %>
	</div>
</div>

app/views/supervisors/courses/show.html.erb
<% provide(:title, @course.name) %>
<h1>Course <%= @course.name%></h1>
<p>
<%= @course.name %> |
<%= @course.description %> | 
<%= link_to "Users attending course", supervisors_course_users_path(@course)  %>
</p>

<p><b>Subjects in course</b></p>
<p>
<% @course.subjects.each do |s| %> 
<%= s.name %> |
<%= s.description %>
<br>
<% end %>
</p>

<p><b>
	<% if current_user.supervisor? %>
	<%= link_to "Edit", edit_supervisors_course_path(@course) %> 
	<% end %>
</p></b>

app/views/supervisors/courses/show_users.html.erb
<h1> Trainees attending course <%= @course %></h1>

<%= will_paginate %>

<ul class="users">
	
  <%= render @users %>
</ul>

<%= will_paginate %>