config/routes.rb
Rails.application.routes.draw do

  root              'static_pages#home'

  get 'help'     => 'static_pages#help'

  get  'contact' => 'static_pages#contact'

  get  'about'   => 'static_pages#about'

  get 'signup' => 'users#new'

  get 'login' => 'sessions#new'

  post 'login' => 'sessions#create'

  delete 'logout' => 'sessions#destroy'

  resources :users do

    resources :courses do

      resources :subjects 

    end

  end

  resources :user_tasks

  namespace :supervisors  do
    match '/login', to: 'sessions#new', via: 'get'
    match '/logout', to: 'sessions#destroy', via: 'delete'
    resources :sessions, only: [:new, :create, :destroy]
    resources :users
    resources :subjects
    resources :courses do
      resources :users
    end
    resources :users_courses, only: [:index, :create]
  end
  

end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password

	has_many :user_courses
	has_many :courses, :through => :user_courses

	has_many :user_subjects
	has_many :subjects, :through => :user_subjects

	has_many :user_tasks
	has_many :tasks, :through => :user_tasks

	validates :password, length: {minimum: 6}, allow_blank: true


	def User.digest(string)
		cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
		BCrypt::Password.create(string, cost: cost)
	end
end

app/controllers/supervisors/users_controller.rb
class Supervisors::UsersController < ApplicationController
  before_action :logged_in_supervisor, only: [:update, :edit]
  before_action :correct_user, only: [:edit, :update]

	def index
		@supervisors = User.where(supervisor: true).all 
    @course = Course.find_by(id: params[:course_id])
    @users = @course.users
	end

  def show
  	@supervisor = User.find(params[:id])
   
  end

 # GET /users/
  def new
  	
  	@supervisor = User.new
  end

  def create
  	@supervisor = User.new(user_params)

  	if @supervisor.save
  		log_in @supervisor
  		# add to flash variable (need to render in views)
  		flash[:success] = "Welcome to ruby on rails"
  		redirect_to superviosrs_user_url(@supervisor)
  	else
  		render 'new'
  	end
  end

  def edit
    @supervisor = User.find_by(id: params[:id])
  end

  def update
    @supervisor = User.find_by(id: params[:id])

    if @supervisor.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to supervisors_user_url(@supervisor)
    else
      render 'edit'
    end
  end

  def destroy
    User.find_by(id: params[:id]).destroy
    redirect_to supervisors_users_url
  end

private
	def user_params
		params.require(:supervisor).permit(:name, :email, :password, :password_confirmation)
	end

  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update, :show]
  before_action :logged_in_supervisor, only: [:index]
  # correct user bao gom chinh' trainee dang login  va cac supervisor
  before_action :correct_user, only: [:edit, :update]


	def index
		@users = User.where(supervisor: false).all.paginate(page: params[:page])
	end
  def show
  	@user = User.find(params[:id])
    @courses = @user.courses.all
    # @subjects = @courses.find(1).subjects.all
  end



 # GET /users/
  def new
  	
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)

  	if @user.save
  		log_in @user
  		# add to flash variable (need to render in views)
  		flash[:success] = "Welcome to ruby on rails"
  		redirect_to user_url(@user)
  	else
  		render 'new'
  	end
  end

  def edit
    @user = User.find_by(id: params[:id])

  end

  def update
    @user = User.find_by(id: params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to user_url(@user)
    else

      render 'edit'
    end
  end

  def destroy
    User.find_by(id: params[:id]).destroy
    flash[:success] = "User deleted! "
    redirect_to users_url
  end



private
# :user o day tuong duong vs @user [?]
	def user_params
		params.require(:user).permit(:name, :email, :password, :password_confirmation)
	end

  
end

app/helpers/users_helper.rb
module UsersHelper

	def gravatar_for(user)
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
		image_tag(gravatar_url, alt: user.name, class: "gravatar")
	end

	def current_user?(user)
		# current_user o day la method <=> get_current_user trong c/java
		user == current_user
	end
end

app/views/users/_user.html.erb
<li>
  	<%= gravatar_for user %>
  	<%= user.name %> |
  	<%= link_to "Details", user_path(user) %> |
  	<%= link_to "View progress", user_courses_path(user) %> |
  	<%= link_to "Edit", edit_user_path(user) %> |
	<%= link_to "Delete", user_path(user), method: :delete, data: {confirm: "Are you sure? "} %>
</li>

app/views/users/course.html.erb
<ul>
<%= @courses.each do |c| %>
<li>
  	<!-- co anh o day -->
  	<%= c.name %> | 
  	<%= link_to "Details", "#" %> | 
  	
</li>

<% end %>

</ul>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <!-- rails send POST if @user.new_record return true, otherwise send PATCH !-->
    <%= form_for(@user) do |f| %>
      <%= render 'shared/errors_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target=_blank>Change</a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<h1> All trainees </h1>

<%= will_paginate %>

<ul class="users">
	
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<h1>Users <%= @user.name%></h1>
<p>
<%= gravatar_for(@user)  %>
<%= @user.name %>
</p>