config/routes.rb
Rails.application.routes.draw do

  root              'static_pages#home'

  get 'help'     => 'static_pages#help'

  get  'contact' => 'static_pages#contact'

  get  'about'   => 'static_pages#about'

  get 'signup' => 'users#new'

  get 'login' => 'sessions#new'

  post 'login' => 'sessions#create'

  delete 'logout' => 'sessions#destroy'

  resources :users do

    resources :courses do

      resources :subjects 

    end

  end

  resources :user_tasks

  namespace :supervisors  do
    match '/login', to: 'sessions#new', via: 'get'
    match '/logout', to: 'sessions#destroy', via: 'delete'
    resources :sessions, only: [:new, :create, :destroy]
    resources :users
    resources :subjects
    resources :courses do
      resources :users
    end
    resources :users_courses, only: [:index, :create]
  end
  

end

app/models/course.rb
class Course < ActiveRecord::Base
	has_many :user_courses
	has_many :users, :through => :user_courses

	has_many :course_subjects
	has_many :subjects, :through => :course_subjects
end

app/models/course_subject.rb
class CourseSubject < ActiveRecord::Base
	belongs_to :course
	belongs_to :subject
end

app/models/subject.rb
class Subject < ActiveRecord::Base
	has_many :tasks

	has_many :course_subjects
	has_many :courses, :through => :course_subjects

	has_many :user_subjects
	has_many :users, :through => :user_subjects

	has_many :tasks
end

app/models/subject_task.rb
class SubjectTask < ActiveRecord::Base
end

app/models/task.rb
class Task < ActiveRecord::Base
	has_many :user_tasks
	has_many :users, :through => :user_tasks

	belongs_to :subject
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password

	has_many :user_courses
	has_many :courses, :through => :user_courses

	has_many :user_subjects
	has_many :subjects, :through => :user_subjects

	has_many :user_tasks
	has_many :tasks, :through => :user_tasks

	validates :password, length: {minimum: 6}, allow_blank: true


	def User.digest(string)
		cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
		BCrypt::Password.create(string, cost: cost)
	end
end

app/models/user_course.rb
class UserCourse < ActiveRecord::Base
	belongs_to :user
	belongs_to :course
end

app/models/user_subject.rb
class UserSubject < ActiveRecord::Base
	belongs_to :user 
	belongs_to :subject 
end

app/models/user_task.rb
class UserTask < ActiveRecord::Base
	belongs_to :user 
	belongs_to :task
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include SessionsHelper
  include Supervisors::SessionsHelper
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
	before_action :logged_in_user, only: [:index, :show]

	def index
		# @user = User.find_by(id: session[:user_id])
		@user = User.find_by(id: params[:user_id])
		@courses = @user.courses.all
	end

	def show
		@course = Course.find_by(id: params[:id])
		
	end

	def new
		
	end

	def create
		
	end

	def edit
		
	end

	def update
		
	end

	def destroy
		
	end

private


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
  	user = User.find_by(email: params[:session][:email].downcase)
  	if( user && user.authenticate(params[:session][:password]) && !user.supervisor? ) 
  		log_in user
  		redirect_to user_path(user)
  	else
  		flash.now[:danger] = 'Invalid email/password combination'
  		render 'new'
  	end
  end

  def destroy
  	log_out
  	redirect_to root_path
  end

end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
	before_action(:logged_in_user, :only => :show)

	def index
		
	end

	def show
		@user = User.find_by(id: params[:user_id])
		@course = Course.find_by(id: params[:course_id])
		@subject = Subject.find_by(id: params[:id])
	end

	def new
		
	end

	# cap nhat tien do. hoc tap.
	# report day by day
	def create
		@task_ids = params[:task_id]
		@course = Course.find_by(id: params[:course_id])
		@subject = Subject.find_by(id: params[:subject_id])
		
		if !@task_ids.nil?
			@task_ids.each do |t|
				@ut = UserTask.new(user_id: current_user.id, task_id: t)
				@ut.save
			end
			# @task = Task.find_by(id: @task_ids.first)
			# @subject = @task.subject  

			# neu hoan thanh subject thi luu vao user_subject
			if finish_subject?(@subject)
				@us = UserSubject.new(user_id: current_user.id, subject_id: @subject.id)
				@us.save
			end
			
			redirect_to	user_course_subject_url(current_user, @course, @subject)
		else

			redirect_to	user_course_subject_url(current_user, @course, @subject)
		end
	end

private 
	# hoan thanh subject <=> hoan thanh tat ca task trong do
	def finish_subject?(subject)

		@tasks = subject.tasks
		@finish_tasks = current_user.tasks

		@tasks.each do |t|
			if !@finish_tasks.include?(t)
				return false
			end
		end

		return true
	end

end

app/controllers/user_tasks_controller.rb
class UserTasksController < ApplicationController
	def create
		@ut = UserTask.new(user_id: current_user.id, task_id: params[:task][:id])
		if @ut.save
			redirect_to subject_url(@subject)
		else

		end
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update, :show]
  before_action :logged_in_supervisor, only: [:index]
  # correct user bao gom chinh' trainee dang login  va cac supervisor
  before_action :correct_user, only: [:edit, :update]


	def index
		@users = User.where(supervisor: false).all.paginate(page: params[:page])
	end
  def show
  	@user = User.find(params[:id])
    @courses = @user.courses.all
    # @subjects = @courses.find(1).subjects.all
  end



 # GET /users/
  def new
  	
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)

  	if @user.save
  		log_in @user
  		# add to flash variable (need to render in views)
  		flash[:success] = "Welcome to ruby on rails"
  		redirect_to user_url(@user)
  	else
  		render 'new'
  	end
  end

  def edit
    @user = User.find_by(id: params[:id])

  end

  def update
    @user = User.find_by(id: params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to user_url(@user)
    else

      render 'edit'
    end
  end

  def destroy
    User.find_by(id: params[:id]).destroy
    flash[:success] = "User deleted! "
    redirect_to users_url
  end



private
# :user o day tuong duong vs @user [?]
	def user_params
		params.require(:user).permit(:name, :email, :password, :password_confirmation)
	end

  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(user)
		session[:user_id] = user.id
		# cai nay phuc vu viec show courses ma user tham gia
		session[:user_course_id] = user.id
		
	end

	def current_user
		@current_user ||= User.find_by(id: session[:user_id])
		
	end

	def logged_in?
		!current_user.nil?
	end

	def log_out
		session.delete(:user_id)
		@current_user = nil
	end

	# confirm login trainee
	def logged_in_trainee
	    unless (logged_in? && !current_user.supervisor?)
	    	log_out
	      	flash[:danger] = "Please log in (as a trainee)."
	      	redirect_to login_url
	    end
	end

	# confirm correct user

	def correct_user

		@user = User.find_by(id: params[:id])
		unless ( @user.supervisor? ? (current_user == @user) : (current_user == @user || current_user.supervisor?) )
			flash[:danger] = "Not correct user."
			redirect_to root_url
		end
		
	end

	# confirm login user
	def logged_in_user
	    unless (logged_in?)
	      flash[:danger] = "Please log in."
	      redirect_to login_url
	    end
	end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_controller_helper.rb
module UsersControllerHelper
end

app/helpers/users_helper.rb
module UsersHelper

	def gravatar_for(user)
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
		image_tag(gravatar_url, alt: user.name, class: "gravatar")
	end

	def current_user?(user)
		# current_user o day la method <=> get_current_user trong c/java
		user == current_user
	end
end

app/views/layouts/_footer.html.erb
<div class="navbar navbar-fixed-bottom ">
  	<div class="container">
      	<%= debug(params) if Rails.env.development? %>
  	</div>
</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top navbar-inverse">
  	<div class="container">
   
   
      	<ul class="nav navbar-nav pull-right">
			<li><%= link_to "Home", root_path %></li>
			<li><%= link_to "Help", help_path %></li>

			<% if logged_in? %>
			<% if current_user.supervisor? %>
			<li><%= link_to "Trainees", users_path %></li>
			<li><%= link_to "Courses", supervisors_courses_path %></li>
			<li><%= link_to "Subjects", supervisors_subjects_path %></li>
			
			<li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">
				Hi,<%= current_user.name %>! <b class="caret"></b>
				</a>
				<ul class="dropdown-menu">
				    <li> <%= link_to "Profile", supervisors_user_path(current_user)  %> </li>
				    <li> <%= link_to "Settings", edit_supervisors_user_path(current_user)  %> </li>
				    
				    <li class="divider">  </li>
				    <li> <%= link_to "Logout", supervisors_logout_path, method: "delete"  %></li>
				</ul>

			</li>
			<% else %>
			<li><%= link_to "Progress", user_courses_path(current_user) %></li>
			<li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">
				Hi, <%= current_user.name %>! <b class="caret"></b>
				</a>

				<ul class="dropdown-menu">
				    <li> <%= link_to "Profile", user_path(current_user)  %> </li>
				    <li> <%= link_to "Settings", edit_user_path(current_user)  %> </li>
				    
				    <li class="divider">  </li>
				    <li> <%= link_to "Logout", logout_path, method: "delete"  %></li>
				</ul>

			</li>

			<% end %>

			<% else %>

			<li><%= link_to "Log in", login_path  %></li>

			<% end %>
      	</ul>
    
  	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %> | Project Ruby on rails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<!-- Wrap all page content here -->
	<div id="wrap">

		<!-- Fixed navbar -->
	  	<%= render 'layouts/header'  %>
	  
	  
	  
	  	<!-- Begin page content -->
	  	<div class="center-container">
	    
	    	<% flash.each do |msg_type, msg| %>
				<div class="alert alert-<%= msg_type %>">
					<%= msg %>
				</div>
			<% end %>

			<%= yield  %>
	    
	  	</div>
	  
	</div>

	
	<%= render 'layouts/footer' %>


</body>
</html>

app/views/shared/_error_messages_course.erb
<% if @course.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@course.errors.count, "error") %>.
    </div>
    <ul>
    <% @course.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_error_messages_supervisors.html.erb
<% if @supervisor.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@supervisor.errors.count, "error") %>.
    </div>
    <ul>
    <% @supervisor.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_errors_messages.html.erb
<% if @user.errors.size > 0 %>
	<div id="error_explanation">
		<% @user.errors.full_messages.each do |msg| %>
			<li> <%= msg  %> </li>
		<% end %>	
	</div>
<% end %>